name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '10 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.0, 7.4]
        laravel: [8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 8.*
            php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress
      - name: Execute Unit Tests
        run: vendor/bin/phpunit

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
